### ISSUE TITLE
excluded projects breaks extraction on sbt 0.13

### ISSUE THREAD

**Issue by adriaanm** [typesafehub/dbuild#172]
from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/35/console:

When removing the "excludes" option, [extraction works](https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/36/)

```
[sbt] --== Extracting dependencies for sbt ==--
[...]
[sbt] [info] Set current project to sbtRoot (in build file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/extraction/5e4bdf013faa7445969819475b8fad707794be02/projects/6c586f0f5cf1f36e3b20760935035d28724a324f/)
[sbt:error] java.lang.RuntimeException: These subprojects were not found: "root", "launch-test".  Found: "datatypeProj", "testingProj", "crossProj", "processProj", "sbtRoot", "scriptedSbtProj", "stdTaskProj", "logicProj", "precompiled-2_9_2", "compileIncrementalProj", "sbtProj", "compilerIntegrationProj", "taskProj", "trackingProj", "allPrecompiled", "compileInterfaceProj", "runProj", "precompiled-2_8_2", "precompiled-2_9_3", "controlProj", "classfileProj", "logProj", "bundledLauncherProj", "mainProj", "compilePersistProj", "applyMacroProj", "scriptedBaseProj", "scriptedPluginProj", "ioProj", "interfaceProj", "completeProj", "apiProj", "cacheProj", "mainSettingsProj", "ivyProj", "actionsProj", "compilerProj", "compilerIvyProj", "collectionProj", "relationProj", "commandProj", "classpathProj", "testAgentProj", "mavenResolverPluginProj". 
[sbt:error] 	at scala.sys.package$.error(package.scala:27)
[sbt:error] 	at com.typesafe.dbuild.DistributedRunner$.verifySubProjects(DistributedRunner.scala:86)
[sbt:error] 	at com.typesafe.dbuild.DistributedRunner$.getSortedProjects(DistributedRunner.scala:92)
[sbt:error] 	at com.typesafe.dbuild.DependencyAnalysis$.printDependencies(DependencyAnalysis.scala:108)
[sbt:error] 	at com.typesafe.dbuild.DependencyAnalysis$$anonfun$printCmd$1.apply(DependencyAnalysis.scala:292)
[sbt:error] 	at com.typesafe.dbuild.DependencyAnalysis$$anonfun$printCmd$1.apply(DependencyAnalysis.scala:292)
[sbt:error] 	at com.typesafe.dbuild.StateHelpers$.saveLastMsg(StateHelpers.scala:35)
[sbt:error] 	at com.typesafe.dbuild.DependencyAnalysis$.printCmd(DependencyAnalysis.scala:293)
[sbt:error] 	at $f501d3a12a179991b75d$$anonfun$$sbtdef$1$$anonfun$apply$1.apply(/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/extraction/5e4bdf013faa7445969819475b8fad707794be02/projects/6c586f0f5cf1f36e3b20760935035d28724a324f/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1)
[sbt:error] 	at $f501d3a12a179991b75d$$anonfun$$sbtdef$1$$anonfun$apply$1.apply(/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/extraction/5e4bdf013faa7445969819475b8fad707794be02/projects/6c586f0f5cf1f36e3b20760935035d28724a324f/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1)
[sbt:error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[sbt:error] 	at sbt.Project$.setProject(Project.scala:319)
[sbt:error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:484)
[sbt:error] 	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
[sbt:error] 	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
[sbt:error] 	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
[sbt:error] 	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
[sbt:error] 	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
[sbt:error] 	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
[sbt:error] 	at sbt.Command$.process(Command.scala:92)
[sbt:error] 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[sbt:error] 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[sbt:error] 	at sbt.State$$anon$1.process(State.scala:184)
[sbt:error] 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[sbt:error] 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[sbt:error] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[sbt:error] 	at sbt.MainLoop$.next(MainLoop.scala:98)
[sbt:error] 	at sbt.MainLoop$.run(MainLoop.scala:91)
[sbt:error] 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
[sbt:error] 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
[sbt:error] 	at sbt.Using.apply(Using.scala:24)
[sbt:error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
[sbt:error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
[sbt:error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
[sbt:error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
[sbt:error] 	at sbt.StandardMain$.runManaged(Main.scala:53)
[sbt:error] 	at sbt.xMain.run(Main.scala:28)
[sbt:error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
[sbt:error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
[sbt:error] 	at xsbt.boot.Launch$.run(Launch.scala:57)
[sbt:error] 	at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
[sbt:error] 	at xsbt.boot.Launch$.launch(Launch.scala:65)
[sbt:error] 	at xsbt.boot.Launch$.apply(Launch.scala:16)
[sbt:error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:32)
[sbt:error] 	at xsbt.boot.Boot$.main(Boot.scala:21)
[sbt:error] 	at xsbt.boot.Boot.main(Boot.scala)
[sbt] java.lang.RuntimeException: These subprojects were not found: "root", "launch-test".  Found: "datatypeProj", "testingProj", "crossProj", "processProj", "sbtRoot", "scriptedSbtProj", "stdTaskProj", "logicProj", "precompiled-2_9_2", "compileIncrementalProj", "sbtProj", "compilerIntegrationProj", "taskProj", "trackingProj", "allPrecompiled", "compileInterfaceProj", "runProj", "precompiled-2_8_2", "precompiled-2_9_3", "controlProj", "classfileProj", "logProj", "bundledLauncherProj", "mainProj", "compilePersistProj", "applyMacroProj", "scriptedBaseProj", "scriptedPluginProj", "ioProj", "interfaceProj", "completeProj", "apiProj", "cacheProj", "mainSettingsProj", "ivyProj", "actionsProj", "compilerProj", "compilerIvyProj", "collectionProj", "relationProj", "commandProj", "classpathProj", "testAgentProj", "mavenResolverPluginProj". 
[sbt] 	at scala.sys.package$.error(package.scala:27)
[sbt] 	at com.typesafe.dbuild.DistributedRunner$.verifySubProjects(DistributedRunner.scala:86)
[sbt] 	at com.typesafe.dbuild.DistributedRunner$.getSortedProjects(DistributedRunner.scala:92)
[sbt] 	at com.typesafe.dbuild.DependencyAnalysis$.printDependencies(DependencyAnalysis.scala:108)
[sbt] 	at com.typesafe.dbuild.DependencyAnalysis$$anonfun$printCmd$1.apply(DependencyAnalysis.scala:292)
[sbt] 	at com.typesafe.dbuild.DependencyAnalysis$$anonfun$printCmd$1.apply(DependencyAnalysis.scala:292)
[sbt] 	at com.typesafe.dbuild.StateHelpers$.saveLastMsg(StateHelpers.scala:35)
[sbt] 	at com.typesafe.dbuild.DependencyAnalysis$.printCmd(DependencyAnalysis.scala:293)
[sbt] 	at $f501d3a12a179991b75d$$anonfun$$sbtdef$1$$anonfun$apply$1.apply(/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/extraction/5e4bdf013faa7445969819475b8fad707794be02/projects/6c586f0f5cf1f36e3b20760935035d28724a324f/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1)
[sbt] 	at $f501d3a12a179991b75d$$anonfun$$sbtdef$1$$anonfun$apply$1.apply(/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/extraction/5e4bdf013faa7445969819475b8fad707794be02/projects/6c586f0f5cf1f36e3b20760935035d28724a324f/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1)
[sbt] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[sbt] 	at sbt.Project$.setProject(Project.scala:319)
[sbt] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:484)
[sbt] 	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
[sbt] 	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
[sbt] 	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
[sbt] 	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
[sbt] 	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
[sbt] 	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
[sbt] 	at sbt.Command$.process(Command.scala:92)
[sbt] 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[sbt] 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[sbt] 	at sbt.State$$anon$1.process(State.scala:184)
[sbt] 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[sbt] 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[sbt] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[sbt] 	at sbt.MainLoop$.next(MainLoop.scala:98)
[sbt] 	at sbt.MainLoop$.run(MainLoop.scala:91)
[sbt] 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
[sbt] 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
[sbt] 	at sbt.Using.apply(Using.scala:24)
[sbt] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
[sbt] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
[sbt] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
[sbt] 	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
[sbt] 	at sbt.StandardMain$.runManaged(Main.scala:53)
[sbt] 	at sbt.xMain.run(Main.scala:28)
[sbt] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
[sbt] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
[sbt] 	at xsbt.boot.Launch$.run(Launch.scala:57)
[sbt] 	at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
[sbt] 	at xsbt.boot.Launch$.launch(Launch.scala:65)
[sbt] 	at xsbt.boot.Launch$.apply(Launch.scala:16)
[sbt] 	at xsbt.boot.Boot$.runImpl(Boot.scala:32)
[sbt] 	at xsbt.boot.Boot$.main(Boot.scala:21)
[sbt] 	at xsbt.boot.Boot.main(Boot.scala)
[sbt] [error] These subprojects were not found: "root", "launch-test".  Found: "datatypeProj", "testingProj", "crossProj", "processProj", "sbtRoot", "scriptedSbtProj", "stdTaskProj", "logicProj", "precompiled-2_9_2", "compileIncrementalProj", "sbtProj", "compilerIntegrationProj", "taskProj", "trackingProj", "allPrecompiled", "compileInterfaceProj", "runProj", "precompiled-2_8_2", "precompiled-2_9_3", "controlProj", "classfileProj", "logProj", "bundledLauncherProj", "mainProj", "compilePersistProj", "applyMacroProj", "scriptedBaseProj", "scriptedPluginProj", "ioProj", "interfaceProj", "completeProj", "apiProj", "cacheProj", "mainSettingsProj", "ivyProj", "actionsProj", "compilerProj", "compilerIvyProj", "collectionProj", "relationProj", "commandProj", "classpathProj", "testAgentProj", "mavenResolverPluginProj". 
[sbt] [error] Use 'last' for the full log.
[sbt] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[sbt:error] java.lang.RuntimeException: These subprojects were not found: "root", "launch-test".  Found: "datatypeProj", "testingProj", "crossProj", "processProj", "sbtRoot", "scriptedSbtProj", "stdTaskProj", "logicProj", "precompiled-2_9_2", "compileIncrementalProj", "sbtProj", "compilerIntegrationProj", "taskProj", "trackingProj", "allPrecompiled", "compileInterfaceProj", "runProj", "precompiled-2_8_2", "precompiled-2_9_3", "controlProj", "classfileProj", "logProj", "bundledLauncherProj", "mainProj", "compilePersistProj", "applyMacroProj", "scriptedBaseProj", "scriptedPluginProj", "ioProj", "interfaceProj", "completeProj", "apiProj", "cacheProj", "mainSettingsProj", "ivyProj", "actionsProj", "compilerProj", "compilerIvyProj", "collectionProj", "relationProj", "commandProj", "classpathProj", "testAgentProj", "mavenResolverPluginProj". 
[sbt:error] 	at scala.sys.package$.error(package.scala:27)
[sbt:error] 	at distributed.support.sbt.SbtRunner.distributed$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:93)
[sbt:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[sbt:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[sbt:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:74)
[sbt:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[sbt:error] 	at sbt.IO$.withTemporaryFile(IO.scala:311)
[sbt:error] 	at distributed.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[sbt:error] 	at distributed.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:99)
[sbt:error] 	at distributed.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:58)
[sbt:error] 	at distributed.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:18)
[sbt] --== End Extracting dependencies for sbt ==--
```

**Comment by cunei** [comment]
The error message above is pretty explicative:
```
These subprojects were not found: "root", "launch-test".  Found: [...]
```
In sbt, the "root" project was renamed, and "launch-test" removed. See:
https://github.com/sbt/sbt/commit/f4e692ca883b745c70a772dfdd995183791fbba8
https://github.com/sbt/sbt/commit/56cc49a6b0863def0008e76fc54e13e956641fb5
So, not a bug.
